name: Build
on: [ push, pull_request ]
permissions:
  attestations: write
  contents: read
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        platform:
          - host: macos-latest
            os_name: mac
            file_name: doom-status

          - host: ubuntu-latest
            os_name: linux
            file_name: doom-status

          - host: windows-latest
            os_name: windows
            file_name: doom-status.exe
    runs-on: ${{ matrix.platform.host }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            archive.ubuntu.com:80
            azure.archive.ubuntu.com:80
            api.github.com:443
            crates.io:443
            esm.ubuntu.com:443
            fulcio.sigstore.dev:443
            github.com:443
            index.crates.io:443
            motd.ubuntu.com:443
            ppa.launchpadcontent.net:443
            rekor.sigstore.dev:443
            security.ubuntu.com:80
            static.crates.io:443
            static.rust-lang.org:443

      - name: Install Dependencies (Linux)
        run: sudo apt-get install -y libgtk-3-dev libglib2.0-dev build-essential
        if: matrix.platform.host == 'ubuntu-latest'

      - name: Install extra tools (Windows)
        uses: ChristopheLav/windows-sdk-install@88d72875fb873886ea398ed04041446da6f26f86 # v1.0.3
        with:
          version-sdk: 22621
          features: 'OptionId.DesktopCPPx64,OptionId.DesktopCPParm64'
        if: matrix.platform.host == 'windows-latest'

      - run: rustup target install aarch64-pc-windows-msvc
        if: matrix.platform.host == 'windows-latest'

      - run: rustup target install x86_64-apple-darwin
        if: matrix.platform.host == 'macos-latest'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Rust toolchain
        run: rustup show && rustup update

      - name: Build
        run: cargo build --release

      - name: Build Windows arm64
        run: cargo build --release --target=aarch64-pc-windows-msvc
        if: matrix.platform.host == 'windows-latest'

      - name: Build Mac x86_64
        run: |
          cargo build --release --target=x86_64-apple-darwin
          lipo -create -output doom-status-universal target/release/doom-status target/x86_64-apple-darwin/release/doom-status
          mv doom-status-universal target/release/${{ matrix.platform.file_name }}
        if: matrix.platform.host == 'macos-latest'

      - uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        with:
          subject-path: target/release/${{ matrix.platform.file_name }}

      - uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        with:
          subject-path: target/aarch64-pc-windows-msvc/release/${{ matrix.platform.file_name }}
        if: matrix.platform.host == 'windows-latest'

      - name: Upload
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: doom-status_${{ matrix.platform.os_name }}
          path: target/release/${{ matrix.platform.file_name }}
          compression-level: 0
          if-no-files-found: error
          retention-days: 5

      - name: Upload
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: doom-status_${{ matrix.platform.os_name }}-arm64
          path: target/aarch64-pc-windows-msvc/release/${{ matrix.platform.file_name }}
          compression-level: 0
          if-no-files-found: error
          retention-days: 5
        if: matrix.platform.host == 'windows-latest'